[workspace]
resolver = "3"
members = [
    "apps/desktop/src-tauri",
    "crates/tf-core",
    "crates/tf-plugin-api",
    "crates/xtask",
    "plugins/*/backend",
]

[workspace.package]
version = "0.1.2"
edition = "2024"
license = "MIT"
authors = ["qianmoQ"]

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1", features = ["preserve_order", "arbitrary_precision"] }
thiserror = "2"
tf-core = { path = "crates/tf-core" }
tf-plugin-api = { path = "crates/tf-plugin-api" }
tfp-encoder = { path = "plugins/encoder/backend" }
tfp-hash = { path = "plugins/hash/backend" }
tfp-json-formatter = { path = "plugins/json-formatter/backend" }
tfp-jwt = { path = "plugins/jwt/backend" }
tfp-regex = { path = "plugins/regex/backend" }
tfp-sql-formatter = { path = "plugins/sql-formatter/backend" }
tfp-text-diff = { path = "plugins/text-diff/backend" }
tfp-text-tools = { path = "plugins/text-tools/backend" }
tfp-timestamp = { path = "plugins/timestamp/backend" }
tfp-uuid = { path = "plugins/uuid/backend" }
tfp-xml-formatter = { path = "plugins/xml-formatter/backend" }

[profile.release]
codegen-units = 1
lto = true
opt-level = "s"
panic = "abort"
strip = true
