//! 内置数据：中文（姓名带拼音、真实的省市与行政区划代码）与英文（姓名、美国城市与州）。

/// （姓，拼音）
pub const ZH_SURNAMES: &[(&str, &str)] = &[
    ("王", "wang"),
    ("李", "li"),
    ("张", "zhang"),
    ("刘", "liu"),
    ("陈", "chen"),
    ("杨", "yang"),
    ("黄", "huang"),
    ("赵", "zhao"),
    ("吴", "wu"),
    ("周", "zhou"),
    ("徐", "xu"),
    ("孙", "sun"),
    ("马", "ma"),
    ("朱", "zhu"),
    ("胡", "hu"),
    ("郭", "guo"),
    ("何", "he"),
    ("林", "lin"),
    ("高", "gao"),
    ("罗", "luo"),
    ("郑", "zheng"),
    ("梁", "liang"),
    ("谢", "xie"),
    ("宋", "song"),
    ("唐", "tang"),
    ("许", "xu"),
    ("韩", "han"),
    ("冯", "feng"),
    ("邓", "deng"),
    ("曹", "cao"),
    ("彭", "peng"),
    ("曾", "zeng"),
    ("肖", "xiao"),
    ("田", "tian"),
    ("董", "dong"),
    ("袁", "yuan"),
    ("潘", "pan"),
    ("于", "yu"),
    ("蒋", "jiang"),
    ("蔡", "cai"),
    ("余", "yu"),
    ("杜", "du"),
    ("叶", "ye"),
    ("程", "cheng"),
    ("苏", "su"),
    ("魏", "wei"),
    ("吕", "lv"),
    ("丁", "ding"),
    ("任", "ren"),
    ("沈", "shen"),
    ("姚", "yao"),
    ("卢", "lu"),
    ("姜", "jiang"),
    ("崔", "cui"),
    ("钟", "zhong"),
    ("谭", "tan"),
    ("陆", "lu"),
    ("汪", "wang"),
    ("范", "fan"),
    ("金", "jin"),
    ("石", "shi"),
    ("廖", "liao"),
    ("贾", "jia"),
    ("夏", "xia"),
    ("韦", "wei"),
    ("方", "fang"),
    ("白", "bai"),
    ("邹", "zou"),
    ("孟", "meng"),
    ("熊", "xiong"),
    ("秦", "qin"),
    ("邱", "qiu"),
    ("江", "jiang"),
    ("尹", "yin"),
    ("薛", "xue"),
    ("闫", "yan"),
    ("段", "duan"),
    ("雷", "lei"),
    ("侯", "hou"),
    ("龙", "long"),
    ("史", "shi"),
    ("陶", "tao"),
    ("黎", "li"),
    ("贺", "he"),
    ("顾", "gu"),
    ("毛", "mao"),
    ("郝", "hao"),
    ("龚", "gong"),
    ("邵", "shao"),
    ("万", "wan"),
    ("欧阳", "ouyang"),
    ("司马", "sima"),
    ("上官", "shangguan"),
    ("诸葛", "zhuge"),
];

/// 男性名用字（字，拼音）
pub const ZH_MALE: &[(&str, &str)] = &[
    ("伟", "wei"),
    ("强", "qiang"),
    ("磊", "lei"),
    ("军", "jun"),
    ("洋", "yang"),
    ("勇", "yong"),
    ("杰", "jie"),
    ("涛", "tao"),
    ("斌", "bin"),
    ("超", "chao"),
    ("明", "ming"),
    ("刚", "gang"),
    ("平", "ping"),
    ("辉", "hui"),
    ("鹏", "peng"),
    ("华", "hua"),
    ("飞", "fei"),
    ("鑫", "xin"),
    ("波", "bo"),
    ("宇", "yu"),
    ("浩", "hao"),
    ("凯", "kai"),
    ("健", "jian"),
    ("俊", "jun"),
    ("帆", "fan"),
    ("帅", "shuai"),
    ("旭", "xu"),
    ("宁", "ning"),
    ("龙", "long"),
    ("林", "lin"),
    ("博", "bo"),
    ("文", "wen"),
    ("志", "zhi"),
    ("晨", "chen"),
    ("轩", "xuan"),
    ("子", "zi"),
    ("浩然", "haoran"),
    ("子轩", "zixuan"),
    ("宇航", "yuhang"),
    ("俊杰", "junjie"),
    ("志强", "zhiqiang"),
    ("建华", "jianhua"),
    ("明辉", "minghui"),
    ("天宇", "tianyu"),
    ("嘉豪", "jiahao"),
    ("思远", "siyuan"),
];

/// 女性名用字
pub const ZH_FEMALE: &[(&str, &str)] = &[
    ("芳", "fang"),
    ("娜", "na"),
    ("敏", "min"),
    ("静", "jing"),
    ("丽", "li"),
    ("艳", "yan"),
    ("娟", "juan"),
    ("霞", "xia"),
    ("秀英", "xiuying"),
    ("桂英", "guiying"),
    ("婷", "ting"),
    ("雪", "xue"),
    ("琳", "lin"),
    ("颖", "ying"),
    ("倩", "qian"),
    ("洁", "jie"),
    ("玲", "ling"),
    ("萍", "ping"),
    ("红", "hong"),
    ("燕", "yan"),
    ("欣", "xin"),
    ("悦", "yue"),
    ("璐", "lu"),
    ("晶", "jing"),
    ("莉", "li"),
    ("雅", "ya"),
    ("瑶", "yao"),
    ("怡", "yi"),
    ("佳", "jia"),
    ("梦琪", "mengqi"),
    ("欣怡", "xinyi"),
    ("诗涵", "shihan"),
    ("雨桐", "yutong"),
    ("梓涵", "zihan"),
    ("思雨", "siyu"),
    ("佳怡", "jiayi"),
    ("若曦", "ruoxi"),
    ("雅婷", "yating"),
    ("晓燕", "xiaoyan"),
];

/// （省，市，六位行政区划代码，邮编前缀，区县）
pub struct Region {
    pub province: &'static str,
    pub city: &'static str,
    pub code: &'static str,
    pub zip: &'static str,
    pub district: &'static str,
}

macro_rules! regions {
    ($(($p:expr, $c:expr, $code:expr, $zip:expr, $d:expr)),* $(,)?) => {
        &[$(Region { province: $p, city: $c, code: $code, zip: $zip, district: $d }),*]
    };
}

pub const ZH_REGIONS: &[Region] = regions![
    ("北京市", "北京市", "110101", "1000", "东城区"),
    ("北京市", "北京市", "110105", "1000", "朝阳区"),
    ("北京市", "北京市", "110108", "1000", "海淀区"),
    ("上海市", "上海市", "310104", "2000", "徐汇区"),
    ("上海市", "上海市", "310115", "2001", "浦东新区"),
    ("天津市", "天津市", "120101", "3000", "和平区"),
    ("重庆市", "重庆市", "500103", "4000", "渝中区"),
    ("广东省", "广州市", "440106", "5106", "天河区"),
    ("广东省", "深圳市", "440305", "5180", "南山区"),
    ("广东省", "深圳市", "440304", "5180", "福田区"),
    ("广东省", "东莞市", "441900", "5230", "东莞市"),
    ("浙江省", "杭州市", "330106", "3100", "西湖区"),
    ("浙江省", "宁波市", "330212", "3150", "鄞州区"),
    ("江苏省", "南京市", "320102", "2100", "玄武区"),
    ("江苏省", "苏州市", "320505", "2150", "虎丘区"),
    ("四川省", "成都市", "510104", "6100", "锦江区"),
    ("湖北省", "武汉市", "420106", "4300", "武昌区"),
    ("湖南省", "长沙市", "430104", "4100", "岳麓区"),
    ("陕西省", "西安市", "610113", "7100", "雁塔区"),
    ("山东省", "济南市", "370102", "2500", "历下区"),
    ("山东省", "青岛市", "370202", "2660", "市南区"),
    ("福建省", "厦门市", "350203", "3610", "思明区"),
    ("福建省", "福州市", "350102", "3500", "鼓楼区"),
    ("河南省", "郑州市", "410105", "4500", "金水区"),
    ("河北省", "石家庄市", "130102", "0500", "长安区"),
    ("安徽省", "合肥市", "340104", "2300", "蜀山区"),
    ("江西省", "南昌市", "360102", "3300", "东湖区"),
    ("辽宁省", "沈阳市", "210102", "1100", "和平区"),
    ("辽宁省", "大连市", "210202", "1160", "中山区"),
    ("吉林省", "长春市", "220102", "1300", "南关区"),
    ("黑龙江省", "哈尔滨市", "230103", "1500", "南岗区"),
    ("云南省", "昆明市", "530102", "6500", "五华区"),
    ("贵州省", "贵阳市", "520102", "5500", "南明区"),
    ("广西壮族自治区", "南宁市", "450103", "5300", "青秀区"),
    ("海南省", "海口市", "460106", "5701", "龙华区"),
    ("山西省", "太原市", "140105", "0300", "小店区"),
    ("甘肃省", "兰州市", "620102", "7300", "城关区"),
    ("内蒙古自治区", "呼和浩特市", "150102", "0100", "新城区"),
    ("新疆维吾尔自治区", "乌鲁木齐市", "650102", "8300", "天山区"),
    ("宁夏回族自治区", "银川市", "640104", "7500", "兴庆区"),
];

pub const ZH_STREETS: &[&str] = &[
    "人民", "解放", "建设", "中山", "和平", "新华", "长江", "黄河", "学院", "科技", "文化", "友谊",
    "光明", "迎宾", "滨江", "湖滨", "花园", "青年", "朝阳", "东风", "胜利", "工业", "世纪", "高新",
];
pub const ZH_STREET_SUFFIXES: &[&str] = &["路", "街", "大道", "大街"];
pub const ZH_COMMUNITIES: &[&str] = &[
    "阳光花园",
    "翠湖苑",
    "锦绣家园",
    "世纪城",
    "滨江国际",
    "金色家园",
    "幸福里",
    "绿地中心",
    "万科城",
    "碧桂园",
    "华府",
    "御景湾",
];

/// 手机号段
pub const ZH_MOBILE_PREFIXES: &[&str] = &[
    "130", "131", "132", "133", "135", "136", "137", "138", "139", "150", "151", "152", "153",
    "155", "156", "157", "158", "159", "166", "173", "177", "180", "181", "182", "183", "185",
    "186", "187", "188", "189", "191", "198", "199",
];
pub const ZH_EMAIL_DOMAINS: &[&str] = &[
    "qq.com",
    "163.com",
    "126.com",
    "sina.com",
    "gmail.com",
    "outlook.com",
    "foxmail.com",
];

pub const ZH_COMPANY_PREFIXES: &[&str] = &[
    "华夏", "腾飞", "瑞达", "鼎盛", "恒信", "中科", "金桥", "博远", "星辰", "智联", "天成", "宏图",
    "锐思", "云帆", "嘉禾", "创新", "海纳", "明德",
];
pub const ZH_COMPANY_INDUSTRIES: &[&str] = &[
    "科技",
    "信息技术",
    "网络科技",
    "软件",
    "电子商务",
    "文化传媒",
    "教育科技",
    "医疗器械",
    "物流",
    "贸易",
    "新能源",
    "智能制造",
];
pub const ZH_COMPANY_SUFFIXES: &[&str] = &["有限公司", "股份有限公司", "集团有限公司"];
pub const ZH_JOBS: &[&str] = &[
    "软件工程师",
    "产品经理",
    "UI 设计师",
    "测试工程师",
    "运维工程师",
    "数据分析师",
    "项目经理",
    "销售经理",
    "市场专员",
    "人力资源专员",
    "财务会计",
    "客服专员",
    "行政助理",
    "架构师",
    "算法工程师",
];
pub const ZH_WORDS: &[&str] = &[
    "我们", "系统", "用户", "数据", "功能", "产品", "服务", "平台", "需要", "可以", "通过", "进行",
    "提供", "支持", "管理", "设计", "开发", "测试", "发布", "优化", "性能", "体验", "安全", "稳定",
    "快速", "简单", "今天", "项目", "团队", "工作", "问题", "解决", "方案", "市场", "客户", "价值",
    "持续", "改进", "目标", "计划", "完成", "重要", "信息", "内容", "页面", "接口", "文档", "版本",
];

pub const EN_FIRST_MALE: &[&str] = &[
    "James",
    "John",
    "Robert",
    "Michael",
    "William",
    "David",
    "Richard",
    "Joseph",
    "Thomas",
    "Charles",
    "Christopher",
    "Daniel",
    "Matthew",
    "Anthony",
    "Mark",
    "Donald",
    "Steven",
    "Paul",
    "Andrew",
    "Joshua",
    "Kevin",
    "Brian",
    "George",
    "Timothy",
    "Ryan",
    "Jacob",
    "Ethan",
    "Noah",
    "Liam",
    "Lucas",
];
pub const EN_FIRST_FEMALE: &[&str] = &[
    "Mary",
    "Patricia",
    "Jennifer",
    "Linda",
    "Elizabeth",
    "Barbara",
    "Susan",
    "Jessica",
    "Sarah",
    "Karen",
    "Lisa",
    "Nancy",
    "Betty",
    "Margaret",
    "Sandra",
    "Ashley",
    "Emily",
    "Donna",
    "Michelle",
    "Carol",
    "Amanda",
    "Melissa",
    "Olivia",
    "Emma",
    "Sophia",
    "Ava",
    "Isabella",
    "Mia",
    "Charlotte",
    "Amelia",
];
pub const EN_LAST: &[&str] = &[
    "Smith",
    "Johnson",
    "Williams",
    "Brown",
    "Jones",
    "Garcia",
    "Miller",
    "Davis",
    "Rodriguez",
    "Martinez",
    "Hernandez",
    "Lopez",
    "Gonzalez",
    "Wilson",
    "Anderson",
    "Thomas",
    "Taylor",
    "Moore",
    "Jackson",
    "Martin",
    "Lee",
    "Perez",
    "Thompson",
    "White",
    "Harris",
    "Sanchez",
    "Clark",
    "Ramirez",
    "Lewis",
    "Robinson",
    "Walker",
    "Young",
    "Allen",
    "King",
    "Wright",
    "Scott",
    "Torres",
    "Nguyen",
    "Hill",
    "Flores",
];

/// （城市，州，州缩写，邮编前缀，电话区号）
pub const EN_CITIES: &[(&str, &str, &str, &str, &str)] = &[
    ("New York", "New York", "NY", "100", "212"),
    ("Los Angeles", "California", "CA", "900", "213"),
    ("San Francisco", "California", "CA", "941", "415"),
    ("San Diego", "California", "CA", "921", "619"),
    ("Chicago", "Illinois", "IL", "606", "312"),
    ("Houston", "Texas", "TX", "770", "713"),
    ("Austin", "Texas", "TX", "787", "512"),
    ("Dallas", "Texas", "TX", "752", "214"),
    ("Phoenix", "Arizona", "AZ", "850", "602"),
    ("Philadelphia", "Pennsylvania", "PA", "191", "215"),
    ("Seattle", "Washington", "WA", "981", "206"),
    ("Denver", "Colorado", "CO", "802", "303"),
    ("Boston", "Massachusetts", "MA", "021", "617"),
    ("Atlanta", "Georgia", "GA", "303", "404"),
    ("Miami", "Florida", "FL", "331", "305"),
    ("Portland", "Oregon", "OR", "972", "503"),
    ("Nashville", "Tennessee", "TN", "372", "615"),
    ("Minneapolis", "Minnesota", "MN", "554", "612"),
    ("Las Vegas", "Nevada", "NV", "891", "702"),
    ("Detroit", "Michigan", "MI", "482", "313"),
];
pub const EN_STREETS: &[&str] = &[
    "Main",
    "Oak",
    "Pine",
    "Maple",
    "Cedar",
    "Elm",
    "Washington",
    "Lake",
    "Hill",
    "Park",
    "Sunset",
    "River",
    "Highland",
    "Madison",
    "Jefferson",
    "Lincoln",
    "Franklin",
    "Church",
    "Spring",
    "Willow",
];
pub const EN_STREET_SUFFIXES: &[&str] = &["St", "Ave", "Blvd", "Rd", "Ln", "Dr", "Way", "Ct"];
pub const EN_EMAIL_DOMAINS: &[&str] = &[
    "gmail.com",
    "yahoo.com",
    "outlook.com",
    "hotmail.com",
    "icloud.com",
    "proton.me",
];
pub const EN_COMPANY_WORDS: &[&str] = &[
    "Acme",
    "Globex",
    "Initech",
    "Umbrella",
    "Stark",
    "Wayne",
    "Hooli",
    "Vandelay",
    "Soylent",
    "Cyberdyne",
    "Northwind",
    "Contoso",
    "Fabrikam",
    "Tailspin",
    "Blue Harbor",
    "Summit",
    "Pioneer",
    "Evergreen",
];
pub const EN_COMPANY_SUFFIXES: &[&str] = &[
    "Inc.",
    "LLC",
    "Group",
    "Labs",
    "Technologies",
    "Holdings",
    "& Co.",
];
pub const EN_JOBS: &[&str] = &[
    "Software Engineer",
    "Product Manager",
    "UX Designer",
    "QA Engineer",
    "DevOps Engineer",
    "Data Analyst",
    "Project Manager",
    "Sales Manager",
    "Marketing Specialist",
    "HR Generalist",
    "Accountant",
    "Support Specialist",
    "Office Assistant",
    "Solutions Architect",
    "Machine Learning Engineer",
];
pub const EN_WORDS: &[&str] = &[
    "lorem",
    "ipsum",
    "dolor",
    "sit",
    "amet",
    "consectetur",
    "adipiscing",
    "elit",
    "sed",
    "do",
    "eiusmod",
    "tempor",
    "incididunt",
    "ut",
    "labore",
    "et",
    "dolore",
    "magna",
    "aliqua",
    "enim",
    "ad",
    "minim",
    "veniam",
    "quis",
    "nostrud",
    "exercitation",
    "ullamco",
    "laboris",
    "nisi",
    "aliquip",
    "ex",
    "ea",
    "commodo",
    "consequat",
    "duis",
    "aute",
    "irure",
    "in",
    "reprehenderit",
    "voluptate",
    "velit",
    "esse",
];
pub const URL_WORDS: &[&str] = &[
    "app", "shop", "blog", "cloud", "data", "news", "hub", "labs", "portal", "store",
];
pub const TLDS: &[&str] = &["com", "net", "org", "io", "dev", "co", "app"];
